version: '2'
networks:
  mired2:
    ipam:
      config:
        - subnet: 182.28.0.0/16
          gateway: 182.28.0.1
services:
  db:
    image: bitnami/mongodb:latest
    container_name: mongo
    networks:
      mired2:
        ipv4_address: 182.28.0.11
    ports:
      - "27017:27017"
    expose:
      - 27017
  agenda:
    image: sarapalma210/sarapalma210:15
    container_name: agendaContactos
    networks:
      mired2:
        ipv4_address: 182.28.0.12
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
